$(document).ready(function(){
    $('.menu_detalle').hide();
    
    $('#tipo1').click(function(){
        $('.menu_detalle').hide();
        $('#menu1').show();
        $('.cubo').css({'background':'#fff'});
        $('#tipo1').css({'background':'rgba(0,0,0,0.2)'});
    });
    $('#tipo2').click(function(){
        $('.menu_detalle').hide();
        $('#menu2').show();
        $('.cubo').css({'background':'#fff'});
        $('#tipo2').css({'background':'rgba(0,0,0,0.2)'});
    });
    $('#tipo3').click(function(){
        $('.menu_detalle').hide();
        $('#menu3').show();
        $('.cubo').css({'background':'#fff'});
        $('#tipo3').css({'background':'rgba(0,0,0,0.2)'});
    });
    $('#tipo4').click(function(){
        $('.menu_detalle').hide();
        $('#menu4').show();
        $('.cubo').css({'background':'#fff'});
        $('#tipo4').css({'background':'rgba(0,0,0,0.2)'});
    });
    $('#tipo5').click(function(){
        $('.menu_detalle').hide();
        $('#menu5').show();
        $('.cubo').css({'background':'#fff'});
        $('#tipo5').css({'background':'rgba(0,0,0,0.2)'});
    });
    $('#tipo6').click(function(){
        $('.menu_detalle').hide();
        $('#menu6').show();
        $('.cubo').css({'background':'#fff'});
        $('#tipo6').css({'background':'rgba(0,0,0,0.2)'});
    });
    $('#tipo7').click(function(){
        $('.menu_detalle').hide();
        $('#menu7').show();
        $('.cubo').css({'background':'#fff'});
        $('#tipo7').css({'background':'rgba(0,0,0,0.2)'});
    });
    $('#tipo8').click(function(){
        $('.menu_detalle').hide();
        $('#menu8').show();
        $('.cubo').css({'background':'#fff'});
        $('#tipo8').css({'background':'rgba(0,0,0,0.2)'});
    });
    $('#tipo9').click(function(){
        $('.menu_detalle').hide();
        $('#menu9').show();
        $('.cubo').css({'background':'#fff'});
        $('#tipo9').css({'background':'rgba(0,0,0,0.2)'});
    });
    $('#tipo10').click(function(){
        $('.menu_detalle').hide();
        $('#menu10').show();
        $('.cubo').css({'background':'#fff'});
        $('#tipo10').css({'background':'rgba(0,0,0,0.2)'});
    });
    $('#tipo11').click(function(){
        $('.menu_detalle').hide();
        $('#menu11').show();
        $('.cubo').css({'background':'#fff'});
        $('#tipo11').css({'background':'rgba(0,0,0,0.2)'});
    });
    $('#tipo12').click(function(){
        $('.menu_detalle').hide();
        $('#menu12').show();
        $('.cubo').css({'background':'#fff'});
        $('#tipo12').css({'background':'rgba(0,0,0,0.2)'});
    });
    $('#tipo13').click(function(){
        $('.menu_detalle').hide();
        $('#menu13').show();
        $('.cubo').css({'background':'#fff'});
        $('#tipo13').css({'background':'rgba(0,0,0,0.2)'});
    });
});